---
title: <br><br><br> Decision Maker Summary
---

<div class = "rightA">
All analysis is uncertain. Whether we are looking at statistics about the past, measurements of the present, or forecasts of the future, there will always be a degree of uncertainty in the outputs.
</div>

<div class = "rightA">
This uncertainty can be critically important to any decisions based on the analysis, as ‘best estimates’ are generally not enough to make an informed decision. For example, Option A may appear better than Option B when looking at the most likely outcome of each, but if the uncertainty in A is greater than in B then it might carry an unacceptable chance of much worse outcomes.
</div>


<div class = "rightA">
Making decisions using uncertain information can be uncomfortable – decisions would be far easier if we knew for sure what the consequences of each choice would be – but this is an unavoidable position, so analysts aspire to provide honest and practical advice on uncertainty.
</div>

<div class = "rightA">
The presence of uncertainty in analysis may not always inspire confidence, but the absence of uncertainty is even worse. Since uncertainty is ever-present, omitting it from analysis leaves it unacknowledged and unassessed. It could be of any size, leaving the true range of possible outcomes entirely unknown. A proper assessment of analytical uncertainty should reassure you that the analysts have considered the limitations in their data and methodology, as well as the inherent randomness in the world, in order to provide an honest assessment of the range of possible outcomes – rather than presenting misplaced confidence in an impossibly accurate estimate.
</div>

<div class = "rightA">
This toolkit has been written for analysts to help them understand and assess the uncertainty in their work, and then to communicate that to the users of their analysis in an effective and helpful way. Feedback from those users – those who commission the work and make decisions informed by it – is crucial to helping refine and improve this guidance.
</div>

<div class = "rightA">
Key points:
<ul>
<li> Consider the full range of possible outcomes when using analysis to inform decisions, not just the ‘best estimate’.</li>
<li> Challenge analysts where information on uncertainty is absent or inadequate. </li>
<li> Ask questions about how to interpret the uncertainty and its implications. </li>
<li> Provide feedback to analysts on the usefulness and effectiveness of how they communicate uncertainty. </li>
