---
title: <br><br><br> Introduction
---


<style type="text/css">

#TOC {
margin-top: 100px;
}

.leftA{
float: left;
width: 100%;
font-weight: bold;
}

.rightA{
float:right;
width: 75%;
}

.leftB{
float: left;
width: 23%;
}
</style>

<div style="clear: both;"></div>

<br>

<div class = "leftB">
Uncertainty analysis: understanding what you don't know
</div>

<div class = "rightA">
Uncertainty is unavoidable when making forecasts of future events or impacts of decisions. Our knowledge of the present is typically  incomplete; and we can’t be sure what will happen in the future. We can reduce uncertainty due to lack of knowledge by obtaining more information, or asking experts for advice. However, we can’t eliminate uncertainty entirely, so we must find ways to describe and communicate it.
</div>

<div class = "rightA">
There is a difference between uncertainty and risk; risk typically refers to the likelihood of a future unplanned event or unintended consequence that can be assigned a numeric probability. Forecasts of risk, like other forecasts, are themselves subject to uncertainty.   For example, the UK Met Office forecasts the risk of rain (“probability of precipitation”) over a five-day period for specific locations using a mathematical computer model of the atmosphere. This forecast is uncertain because the initial state of the atmosphere is not perfectly known, and because small perturbations can lead to large weather changes. This uncertainty is described using a range from running several forecasts from equally likely initial conditions.
</div>

<div class = "rightA">
Taking account of uncertainty – and being seen to do so – is important for public trust. We must not pretend that the consequences of a policy or decision are certain: they are always uncertain to some degree. For each option, a range of outcomes are possible. Implying certainty about one particular   outcome can damage public trust when things turn out differently.
</div>

<div class = "leftB">
Why does it matter?
</div>

<div class = "rightA">
Red River Flood, Grand Forks USA, 1997
</div>

<div class = "leftB">
Example
</div>

<div class = "rightA">
The National Weather Service (NWS) predicted, 2 months in advance, the Red River to crest 49 feet.
</div>

<div class = "leftB">
Analysis
</div>

<div class = "rightA">
In response, the levees were built to handle a flood of 51 feet
</div>

<div class = "leftB">
Decision
</div>

<div class = "rightA">
The actual flood level was 54 feet
</div>

<div class = "leftB">
Result
</div>

<div class = "rightA">
Had the NWS communicated their uncertainty (+/- 9 feet) the several $billion damages could have been avoided
</div>

<div class = "leftB">
Uncertainty
</div>

<div style="clear: both;"></div>

```{r fig.align="center", echo=FALSE}

comb2pngs <- function(imgs, bottom_text = NULL){
  img1 <-  grid::rasterGrob(as.raster(png::readPNG(imgs[1])),
                            interpolate = FALSE)
  img2 <-  grid::rasterGrob(as.raster(png::readPNG(imgs[2])),
                            interpolate = FALSE)
  pdp::grid.arrange(img1, img2, ncol = 2, bottom = bottom_text)
}

png1_dest <- "images/Flood_uncertainty.png"
png2_dest <- "images/Flood_damage.png"

comb2pngs(c(png1_dest, png2_dest))


```
<div class = "leftB">
Is this toolkit for you?
</div>

<div class = "rightA">
This toolkit is aimed at all analysts, whether you are new to the Government or an experienced analyst looking to develop the way you communicate uncertainty to stakeholders. 
</div>

<div class = "rightA">
This document sits alongside the Aqua Book guidance on quality analysis. The Aqua Book should be read first as it describes the principles of uncertainty analysis and the processes that should be used in considering it. This is a supplementary document providing additional information for identifying, estimating and communicating uncertainty in analysis to support decisions and decision-makers.  
</div>

<div class = "rightA">
We have also provided a one-page summary of key messages for analysts that can also be shared with decision-makers.
</div>

<div class = "rightA">
1. Asking the right question
2. Defining and identifying uncertainty
3. Understanding and measuring uncertainty
4. Presenting and communicating uncertainty
</div>

<div class = "leftB">
Toolkit contents
</div>

<div class = "rightA">
Before conducting any uncertainty analysis, it is important to check that you understand how the analysis will be used. What type of decision is being made? Is it a financial, operational, policy or other type of decision? This will frame how you approach the analysis and how you communicate it to your customers. 
</div>

<div class = "leftB">
1. Understanding the policy context
</div>

<div class = "rightA">
Considering the whole system that influences your analysis helps identify all possible areas where uncertainty can arise. Ensure you understand what is causing the uncertainty in your inputs and outputs, and whether this can be quantified.
</div>

<div class = "leftB">
2. Sources of uncertainty
</div>

<div class = "rightA">
Before conducting uncertainty analysis, you should consider the range of possible scenarios and techniques. We provide a list of the most common techniques with some examples for reference.
</div>

<div class = "leftB">
3. Conducting uncertainty analysis
</div>

<div class = "rightA">
There is little point conducting any analysis if it has no impact, so this is perhaps the most important chapter. It is important to engage with your stakeholders so they take account of uncertainty in any decisions they make. You should think about how you interact with the audience, tailoring your communication to different groups. This will help them to understand the consequences of uncertainty and why they should be interested in it.
</div>

<div class = "leftB">
4. Presenting and communicating uncertainty
</div>







